apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: userauthconfig-operator
rules:
- apiGroups:
  - security.anthos.io
  resources:
  - userauthconfigs
  - userauthconfigs/status
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources:
  - secrets
  resourceNames:
  - "oauth-secret"  # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.user-auth.oidc.oauthCredentialsSecret.name"}
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: userauthconfig-operation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: userauthconfig-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: asm-user-auth
