apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: userauthconfig-operator
rules:
- resources:
  - userauthconfigs
  - userauthconfigs/status
  apiGroups:
  - security.anthos.io
  verbs: ["get", "update", "patch"]
- resources:
  - secrets
  apiGroups: [""]
  resourceNames:
  - "oauth-secret"  # kpt-set: ${secret-name}
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: userauthconfig-operation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: userauthconfig-operator
subjects:
- name: default
  namespace: asm-user-auth
  kind: ServiceAccount
