apiVersion: v1
kind: ConfigMap
metadata:
  name: user-auth-config
  namespace: asm-user-auth
data:
  config.yaml: |
    config:
      info_service:
        socket_address:
          addr: "0.0.0.0"
          port: 9901
      adapter:
        envoy:
          socket_address:
            addr: "0.0.0.0"
            port: 10003
          failure_mode_allow: false
          enable_plaintext_mode: true
      authentication_plugin:
        enabled: all
      custom_resource_definition_info:
        api_group: "security.anthos.io"
        version: "v1beta1"
        namespace: "asm-user-auth"
        name: "user-auth-config"
        kind_plural_name: "userauthconfigs"
        kind_singular_name: "userauthconfig"
        status_property_name: "userAuthService"
      webflow:
        enabled: true
        logout_destination_uri: "www.example.com/logout"
      login_and_session:
        state_session_encryption_key:
            filename: "/etc/ais/certs/session_cookie.key"
      sts_token:
        sts_token_encryption_key:
          filename: "/etc/ais/certs/session_cookie.key"
      rc_token:
        rc_token_signing_key:
          filename: "/etc/ais/certs/rctoken.key"
