# The following gateway is serving the OIDC termination requests as well as
# the application traffic.
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: userauth
  namespace: asm-user-auth
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: https
      protocol: HTTPS
      number: 443
    hosts:  # kpt-set ${hosts}
    - '*'
    tls:
      credentialName: userauth-tls-cert
      mode: SIMPLE